// A realistically large enum, to show the generated code at scale: see Generated/.../HttpHeader.FancyEnum.g.cs.
//
// With 90 members, the parsers switch strategies. Text parsing dispatches on the input's length to one small
// private helper per length, each a switch over that length's names (plus upper-cased twins for ignore-case). UTF-8
// parsing switches, per length, on the input's first 8 bytes packed into a ulong. ToStringFancy() returns the wire
// name, and NameBytes gives the same name as UTF-8 for writing a header back out.
using FancyEnumGenerator.Attributes;

[FancyEnum(
    DefaultToStringBehavior = FancyEnumDefaultToStringBehavior.CustomFieldFallback, // Unknown has no wire name
    DefaultToStringCustomField = "Name",
    ParseCaseSensitive = false, // header names are case-insensitive (RFC 9110)
    CreateByteParsing = true)]
[FancyEnumMemberMappingSettings("Name", IncludeUtf8Value = true)]
public enum HttpHeader
{
    Unknown = 0,
    [FancyEnumMember("Name", "Accept")] Accept,
    [FancyEnumMember("Name", "Accept-Charset")] AcceptCharset,
    [FancyEnumMember("Name", "Accept-Encoding")] AcceptEncoding,
    [FancyEnumMember("Name", "Accept-Language")] AcceptLanguage,
    [FancyEnumMember("Name", "Accept-Ranges")] AcceptRanges,
    [FancyEnumMember("Name", "Access-Control-Allow-Credentials")] AccessControlAllowCredentials,
    [FancyEnumMember("Name", "Access-Control-Allow-Headers")] AccessControlAllowHeaders,
    [FancyEnumMember("Name", "Access-Control-Allow-Methods")] AccessControlAllowMethods,
    [FancyEnumMember("Name", "Access-Control-Allow-Origin")] AccessControlAllowOrigin,
    [FancyEnumMember("Name", "Access-Control-Expose-Headers")] AccessControlExposeHeaders,
    [FancyEnumMember("Name", "Access-Control-Max-Age")] AccessControlMaxAge,
    [FancyEnumMember("Name", "Access-Control-Request-Headers")] AccessControlRequestHeaders,
    [FancyEnumMember("Name", "Access-Control-Request-Method")] AccessControlRequestMethod,
    [FancyEnumMember("Name", "Age")] Age,
    [FancyEnumMember("Name", "Allow")] Allow,
    [FancyEnumMember("Name", "Alt-Svc")] AltSvc,
    [FancyEnumMember("Name", "Authorization")] Authorization,
    [FancyEnumMember("Name", "Cache-Control")] CacheControl,
    [FancyEnumMember("Name", "Clear-Site-Data")] ClearSiteData,
    [FancyEnumMember("Name", "Connection")] Connection,
    [FancyEnumMember("Name", "Content-Disposition")] ContentDisposition,
    [FancyEnumMember("Name", "Content-Encoding")] ContentEncoding,
    [FancyEnumMember("Name", "Content-Language")] ContentLanguage,
    [FancyEnumMember("Name", "Content-Length")] ContentLength,
    [FancyEnumMember("Name", "Content-Location")] ContentLocation,
    [FancyEnumMember("Name", "Content-Range")] ContentRange,
    [FancyEnumMember("Name", "Content-Security-Policy")] ContentSecurityPolicy,
    [FancyEnumMember("Name", "Content-Security-Policy-Report-Only")] ContentSecurityPolicyReportOnly,
    [FancyEnumMember("Name", "Content-Type")] ContentType,
    [FancyEnumMember("Name", "Cookie")] Cookie,
    [FancyEnumMember("Name", "Cross-Origin-Embedder-Policy")] CrossOriginEmbedderPolicy,
    [FancyEnumMember("Name", "Cross-Origin-Opener-Policy")] CrossOriginOpenerPolicy,
    [FancyEnumMember("Name", "Cross-Origin-Resource-Policy")] CrossOriginResourcePolicy,
    [FancyEnumMember("Name", "Date")] Date,
    [FancyEnumMember("Name", "ETag")] ETag,
    [FancyEnumMember("Name", "Expect")] Expect,
    [FancyEnumMember("Name", "Expires")] Expires,
    [FancyEnumMember("Name", "Forwarded")] Forwarded,
    [FancyEnumMember("Name", "From")] From,
    [FancyEnumMember("Name", "Host")] Host,
    [FancyEnumMember("Name", "If-Match")] IfMatch,
    [FancyEnumMember("Name", "If-Modified-Since")] IfModifiedSince,
    [FancyEnumMember("Name", "If-None-Match")] IfNoneMatch,
    [FancyEnumMember("Name", "If-Range")] IfRange,
    [FancyEnumMember("Name", "If-Unmodified-Since")] IfUnmodifiedSince,
    [FancyEnumMember("Name", "Keep-Alive")] KeepAlive,
    [FancyEnumMember("Name", "Last-Modified")] LastModified,
    [FancyEnumMember("Name", "Link")] Link,
    [FancyEnumMember("Name", "Location")] Location,
    [FancyEnumMember("Name", "Max-Forwards")] MaxForwards,
    [FancyEnumMember("Name", "Origin")] Origin,
    [FancyEnumMember("Name", "Permissions-Policy")] PermissionsPolicy,
    [FancyEnumMember("Name", "Pragma")] Pragma,
    [FancyEnumMember("Name", "Priority")] Priority,
    [FancyEnumMember("Name", "Proxy-Authenticate")] ProxyAuthenticate,
    [FancyEnumMember("Name", "Proxy-Authorization")] ProxyAuthorization,
    [FancyEnumMember("Name", "Range")] Range,
    [FancyEnumMember("Name", "Referer")] Referer,
    [FancyEnumMember("Name", "Referrer-Policy")] ReferrerPolicy,
    [FancyEnumMember("Name", "Retry-After")] RetryAfter,
    [FancyEnumMember("Name", "Sec-Fetch-Dest")] SecFetchDest,
    [FancyEnumMember("Name", "Sec-Fetch-Mode")] SecFetchMode,
    [FancyEnumMember("Name", "Sec-Fetch-Site")] SecFetchSite,
    [FancyEnumMember("Name", "Sec-Fetch-User")] SecFetchUser,
    [FancyEnumMember("Name", "Sec-WebSocket-Accept")] SecWebSocketAccept,
    [FancyEnumMember("Name", "Sec-WebSocket-Extensions")] SecWebSocketExtensions,
    [FancyEnumMember("Name", "Sec-WebSocket-Key")] SecWebSocketKey,
    [FancyEnumMember("Name", "Sec-WebSocket-Protocol")] SecWebSocketProtocol,
    [FancyEnumMember("Name", "Sec-WebSocket-Version")] SecWebSocketVersion,
    [FancyEnumMember("Name", "Server")] Server,
    [FancyEnumMember("Name", "Server-Timing")] ServerTiming,
    [FancyEnumMember("Name", "Set-Cookie")] SetCookie,
    [FancyEnumMember("Name", "Strict-Transport-Security")] StrictTransportSecurity,
    [FancyEnumMember("Name", "TE")] Te,
    [FancyEnumMember("Name", "Timing-Allow-Origin")] TimingAllowOrigin,
    [FancyEnumMember("Name", "Trailer")] Trailer,
    [FancyEnumMember("Name", "Transfer-Encoding")] TransferEncoding,
    [FancyEnumMember("Name", "Upgrade")] Upgrade,
    [FancyEnumMember("Name", "Upgrade-Insecure-Requests")] UpgradeInsecureRequests,
    [FancyEnumMember("Name", "User-Agent")] UserAgent,
    [FancyEnumMember("Name", "Vary")] Vary,
    [FancyEnumMember("Name", "Via")] Via,
    [FancyEnumMember("Name", "WWW-Authenticate")] WwwAuthenticate,
    [FancyEnumMember("Name", "X-Content-Type-Options")] XContentTypeOptions,
    [FancyEnumMember("Name", "X-Forwarded-For")] XForwardedFor,
    [FancyEnumMember("Name", "X-Forwarded-Host")] XForwardedHost,
    [FancyEnumMember("Name", "X-Forwarded-Proto")] XForwardedProto,
    [FancyEnumMember("Name", "X-Frame-Options")] XFrameOptions,
    [FancyEnumMember("Name", "X-Request-Id")] XRequestId,
}
