namespace FancyEnumGenerator;

internal static class FancyEnumCodeWriterDefaults
{
    public static void FancyEnumNewFile(CodeWriter writer)
    {
        writer.WriteComment("<auto-generated/>");
        writer.AppendLine("#nullable enable");
        // With IncludeObsolete, generated code references [Obsolete] members: CS0612 is [Obsolete] with no message,
        // CS0618 is [Obsolete("message")]. Neither is actionable by the consumer, so neither may leak out of here.
        writer.AppendLine("#pragma warning disable CS0612, CS0618");
    }
}
